<?php
echo "<b>Post Increment</b>";
echo "<br/>";
$no =1;
echo "No. Awal : ";
echo $no;
echo "<br/>";
echo "No.Proses Post Increment: ";
echo $no++;
echo "<br/>";
echo "No. Setelah Post Increment: ";
echo $no;
echo "<br/>";
echo "<br/>";
echo "<b>Pre Increment</b>";
echo "<br/>";
$no = 1;
echo "No. Awal : ";
echo $no;
echo "<br/>";
echo "No. Proses Pre Increment: ";
echo ++$no;
echo "<br/>";
echo "No. Setelah Pre Increment: ";
echo $no;
echo "<br/>";
echo "<br/>";
echo "<b>Post Decrement</b>";
echo "<br/>";
$no =1;
echo "No Awal : ";
echo $no;
echo "<br/>";
echo "No Proses Post Decrement: ";
echo $no--;
echo "<br/>";
echo "No. Setelah Post Decrement : ";
echo $no;
echo "<br/>";
echo "<br/>";
echo "<b>Pre Decrement</b>";
echo "<br/>";
$no =1;
echo "No. Awal : ";
echo $no;
echo "<br/>";
echo "No. Proses Pre Decrement: ";
echo --$no;
echo "<br/>";
echo "No. Setelah Pre Decrement : ";
echo $no;
